blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://vkbottle.readthedocs.io/ru/latest/tutorial/faq/
    about: Документация с ответами на часто задаваемые вопросы
  - name: Чат telegram
    url: https://t.me/vkbottle_ru/120804
    about: Здесь вы можете задать вопросы касательно фреймворка
