name: Build

on:
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.repository == 'vkbottle/vkbottle'
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.11"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
